# Generated by Django 5.0.6 on 2024-06-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_producttransaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
